def get_obp_workflow():
    return """SELECT 
    OPB_SUBJECT.SUBJ_NAME SUBJECT_AREA, 
    OPB_TASK.TASK_NAME WORKFLOW_NAME, 
    OPB_SCHEDULER.SCHEDULER_NAME,
    OPB_SCHEDULER.START_TIME,
    OPB_SCHEDULER.END_TIME,
    OPB_SCHEDULER.IS_RUN_ON_LIMIT,
    OPB_SCHEDULER.RUN_OPTIONS,
    OPB_SCHEDULER.END_OPTIONS,
    OPB_SCHEDULER.DELTA_VALUE,
    OPB_SCHEDULER.RUN_COUNT,
    OPB_SCHEDULER.SCHEDULER_ID,
    OPB_SCHEDULER.IS_REUSABLE SCHEDULER_IS_REUSABLE,
    OPB_SCHEDULER.COMMENTS SCHEDULER_COMMENTS,
    OPB_SCHEDULER.VERSION_NUMBER SCHEDULER_VERSION_NUMBER,
    OPB_TASK.VERSION_NUMBER WORKFLOW_VERSION_NUMBER,
    OPB_TASK.TASK_ID WORKFLOW_ID, 
    OPB_TASK.SAVED_VALID WORKFLOW_IS_VALID, 
    OPB_WORKFLOW.IS_SERVICE WORKFLOW_IS_SERVICE, 
    OPB_WORKFLOW.IS_SVC_RUNNABLE WORKFLOW_IS_RUNNABLE_SERVICE, 
    OPB_TASK.LAST_SAVED WORKFLOW_LAST_SAVED, 
    OPB_TASK.COMMENTS WORKFLOW_COMMENTS,
    OPB_SUBJECT.SUBJ_ID SUBJECT_ID, 
    OPB_SERVER_INFO.SERVER_NAME,
    OPB_SERVER_INFO.SERVER_ID,
    1 WORKFLOW_IS_IMPACTED
FROM 
    OPB_TASK, OPB_SERVER_INFO, OPB_SCHEDULER, OPB_WORKFLOW, OPB_SUBJECT
WHERE
    OPB_WORKFLOW.WORKFLOW_ID = OPB_TASK.TASK_ID AND
    OPB_TASK.TASK_TYPE = 71 AND
    OPB_TASK.SUBJECT_ID = OPB_SUBJECT.SUBJ_ID AND
    OPB_TASK.VERSION_NUMBER = OPB_WORKFLOW.VERSION_NUMBER AND
    OPB_TASK.IS_VISIBLE = 1 AND
    OPB_SCHEDULER.IS_VISIBLE = 1 AND
    OPB_WORKFLOW.SCHEDULER_ID = OPB_SCHEDULER.SCHEDULER_ID AND
    OPB_WORKFLOW.SERVER_ID = OPB_SERVER_INFO.SERVER_ID AND
    OPB_SERVER_INFO.SERVER_TYPE = 41
    AND (OPB_TASK.IS_INVALIDATED = 1
    OR EXISTS (SELECT * FROM OPB_TASK_INST I, OPB_TASK T, OPB_VALIDATE V
        WHERE OPB_TASK.TASK_ID = I.WORKFLOW_ID
        AND OPB_TASK.VERSION_NUMBER = I.VERSION_NUMBER
        AND T.TASK_ID = I.TASK_ID
        AND T.TASK_TYPE = I.TASK_TYPE
        AND T.IS_VISIBLE <> 2
        AND V.OBJECT_TYPE = T.TASK_TYPE
        AND V.OBJECT_ID = T.TASK_ID
        AND V.VERSION_NUMBER = T.VERSION_NUMBER
        AND V.INV_UTC > OPB_TASK.UTC_LAST_SAVED))
UNION ALL
SELECT 
    OPB_SUBJECT.SUBJ_NAME SUBJECT_AREA, 
    OPB_TASK.TASK_NAME WORKFLOW_NAME, 
    OPB_SCHEDULER.SCHEDULER_NAME,
    OPB_SCHEDULER.START_TIME,
    OPB_SCHEDULER.END_TIME,
    OPB_SCHEDULER.IS_RUN_ON_LIMIT,
    OPB_SCHEDULER.RUN_OPTIONS,
    OPB_SCHEDULER.END_OPTIONS,
    OPB_SCHEDULER.DELTA_VALUE,
    OPB_SCHEDULER.RUN_COUNT,
    OPB_SCHEDULER.SCHEDULER_ID,
    OPB_SCHEDULER.IS_REUSABLE SCHEDULER_IS_REUSABLE,
    OPB_SCHEDULER.COMMENTS SCHEDULER_COMMENTS,
    OPB_SCHEDULER.VERSION_NUMBER SCHEDULER_VERSION_NUMBER,
    OPB_TASK.VERSION_NUMBER WORKFLOW_VERSION_NUMBER,
    OPB_TASK.TASK_ID WORKFLOW_ID, 
    OPB_TASK.SAVED_VALID WORKFLOW_IS_VALID, 
    OPB_WORKFLOW.IS_SERVICE WORKFLOW_IS_SERVICE, 
    OPB_WORKFLOW.IS_SVC_RUNNABLE WORKFLOW_IS_RUNNABLE_SERVICE, 
    OPB_TASK.LAST_SAVED WORKFLOW_LAST_SAVED, 
    OPB_TASK.COMMENTS WORKFLOW_COMMENTS,
    OPB_SUBJECT.SUBJ_ID SUBJECT_ID, 
    OPB_SERVER_INFO.SERVER_NAME,
    OPB_SERVER_INFO.SERVER_ID,
    0 WORKFLOW_IS_IMPACTED
FROM 
    OPB_TASK, OPB_SERVER_INFO, OPB_SCHEDULER, OPB_WORKFLOW, OPB_SUBJECT
WHERE
    OPB_WORKFLOW.WORKFLOW_ID = OPB_TASK.TASK_ID AND
    OPB_TASK.TASK_TYPE = 71 AND
    OPB_TASK.SUBJECT_ID = OPB_SUBJECT.SUBJ_ID AND
    OPB_TASK.VERSION_NUMBER = OPB_WORKFLOW.VERSION_NUMBER AND
    OPB_TASK.IS_VISIBLE = 1 AND
    OPB_SCHEDULER.IS_VISIBLE = 1 AND
    OPB_WORKFLOW.SCHEDULER_ID = OPB_SCHEDULER.SCHEDULER_ID AND
    OPB_WORKFLOW.SERVER_ID = OPB_SERVER_INFO.SERVER_ID AND
    OPB_SERVER_INFO.SERVER_TYPE = 41
    AND OPB_TASK.IS_INVALIDATED = 0
    AND NOT EXISTS (SELECT * FROM OPB_TASK_INST I, OPB_TASK T, OPB_VALIDATE V
        WHERE OPB_TASK.TASK_ID = I.WORKFLOW_ID
        AND OPB_TASK.VERSION_NUMBER = I.VERSION_NUMBER
        AND T.TASK_ID = I.TASK_ID
        AND T.TASK_TYPE = I.TASK_TYPE
        AND T.IS_VISIBLE <> 2
        AND V.OBJECT_TYPE = T.TASK_TYPE
        AND V.OBJECT_ID = T.TASK_ID
        AND V.VERSION_NUMBER = T.VERSION_NUMBER
        AND V.INV_UTC > OPB_TASK.UTC_LAST_SAVED)
UNION ALL
SELECT 
    OPB_SUBJECT.SUBJ_NAME SUBJECT_AREA, 
    OPB_TASK.TASK_NAME WORKFLOW_NAME, 
    NULL SCHEDULER_NAME,
    NULL START_TIME,
    NULL END_TIME,
    NULL IS_RUN_ON_LIMIT,
    NULL RUN_OPTIONS,
    NULL END_OPTIONS,
    NULL DELTA_VALUE,
    NULL RUN_COUNT,
    NULL SCHEDULER_ID,
    NULL SCHEDULER_IS_REUSABLE,
    NULL SCHEDULER_COMMENTS,
    NULL SCHEDULER_VERSION_NUMBER,
    OPB_TASK.VERSION_NUMBER WORKFLOW_VERSION_NUMBER,
    OPB_TASK.TASK_ID WORKFLOW_ID, 
    OPB_TASK.SAVED_VALID WORKFLOW_IS_VALID, 
    OPB_WORKFLOW.IS_SERVICE WORKFLOW_IS_SERVICE, 
    OPB_WORKFLOW.IS_SVC_RUNNABLE WORKFLOW_IS_RUNNABLE_SERVICE, 
    OPB_TASK.LAST_SAVED WORKFLOW_LAST_SAVED, 
    OPB_TASK.COMMENTS WORKFLOW_COMMENTS,
    OPB_SUBJECT.SUBJ_ID SUBJECT_ID, 
    OPB_SERVER_INFO.SERVER_NAME,
    OPB_SERVER_INFO.SERVER_ID,
    1 WORKFLOW_IS_IMPACTED
FROM 
    OPB_TASK, OPB_SERVER_INFO, OPB_WORKFLOW, OPB_SUBJECT
WHERE
    OPB_WORKFLOW.WORKFLOW_ID = OPB_TASK.TASK_ID AND
    OPB_TASK.TASK_TYPE = 71 AND
    OPB_TASK.SUBJECT_ID = OPB_SUBJECT.SUBJ_ID AND
    OPB_TASK.VERSION_NUMBER = OPB_WORKFLOW.VERSION_NUMBER AND
    OPB_TASK.IS_VISIBLE = 1 AND
    OPB_WORKFLOW.SERVER_ID = OPB_SERVER_INFO.SERVER_ID AND
    OPB_SERVER_INFO.SERVER_TYPE = 41 AND
    OPB_WORKFLOW.SCHEDULER_ID NOT IN (SELECT SCHEDULER_ID FROM OPB_SCHEDULER)
    AND (OPB_TASK.IS_INVALIDATED = 1
    OR EXISTS (SELECT * FROM OPB_TASK_INST I, OPB_TASK T, OPB_VALIDATE V
        WHERE OPB_TASK.TASK_ID = I.WORKFLOW_ID
        AND OPB_TASK.VERSION_NUMBER = I.VERSION_NUMBER
        AND T.TASK_ID = I.TASK_ID
        AND T.TASK_TYPE = I.TASK_TYPE
        AND T.IS_VISIBLE <> 2
        AND V.OBJECT_TYPE = T.TASK_TYPE
        AND V.OBJECT_ID = T.TASK_ID
        AND V.VERSION_NUMBER = T.VERSION_NUMBER
        AND V.INV_UTC > OPB_TASK.UTC_LAST_SAVED))
UNION ALL
SELECT 
    OPB_SUBJECT.SUBJ_NAME SUBJECT_AREA, 
    OPB_TASK.TASK_NAME WORKFLOW_NAME, 
    NULL SCHEDULER_NAME,
    NULL START_TIME,
    NULL END_TIME,
    NULL IS_RUN_ON_LIMIT,
    NULL RUN_OPTIONS,
    NULL END_OPTIONS,
    NULL DELTA_VALUE,
    NULL RUN_COUNT,
    NULL SCHEDULER_ID,
    NULL SCHEDULER_IS_REUSABLE,
    NULL SCHEDULER_COMMENTS,
    NULL SCHEDULER_VERSION_NUMBER,
    OPB_TASK.VERSION_NUMBER WORKFLOW_VERSION_NUMBER,
    OPB_TASK.TASK_ID WORKFLOW_ID, 
    OPB_TASK.SAVED_VALID WORKFLOW_IS_VALID, 
    OPB_WORKFLOW.IS_SERVICE WORKFLOW_IS_SERVICE, 
    OPB_WORKFLOW.IS_SVC_RUNNABLE WORKFLOW_IS_RUNNABLE_SERVICE, 
    OPB_TASK.LAST_SAVED WORKFLOW_LAST_SAVED, 
    OPB_TASK.COMMENTS WORKFLOW_COMMENTS,
    OPB_SUBJECT.SUBJ_ID SUBJECT_ID, 
    OPB_SERVER_INFO.SERVER_NAME,
    OPB_SERVER_INFO.SERVER_ID,
    0 WORKFLOW_IS_IMPACTED
FROM 
    OPB_TASK, OPB_SERVER_INFO, OPB_WORKFLOW, OPB_SUBJECT
WHERE
    OPB_WORKFLOW.WORKFLOW_ID = OPB_TASK.TASK_ID AND
    OPB_TASK.TASK_TYPE = 71 AND
    OPB_TASK.SUBJECT_ID = OPB_SUBJECT.SUBJ_ID AND
    OPB_TASK.VERSION_NUMBER = OPB_WORKFLOW.VERSION_NUMBER AND
    OPB_TASK.IS_VISIBLE = 1 AND
    OPB_WORKFLOW.SERVER_ID = OPB_SERVER_INFO.SERVER_ID AND
    OPB_SERVER_INFO.SERVER_TYPE = 41 AND
    OPB_WORKFLOW.SCHEDULER_ID NOT IN (SELECT SCHEDULER_ID FROM OPB_SCHEDULER)
    AND OPB_TASK.IS_INVALIDATED = 0
    AND NOT EXISTS (SELECT * FROM OPB_TASK_INST I, OPB_TASK T, OPB_VALIDATE V
        WHERE OPB_TASK.TASK_ID = I.WORKFLOW_ID
        AND OPB_TASK.VERSION_NUMBER = I.VERSION_NUMBER
        AND T.TASK_ID = I.TASK_ID
        AND T.TASK_TYPE = I.TASK_TYPE
        AND T.IS_VISIBLE <> 2
        AND V.OBJECT_TYPE = T.TASK_TYPE
        AND V.OBJECT_ID = T.TASK_ID
        AND V.VERSION_NUMBER = T.VERSION_NUMBER
        AND V.INV_UTC > OPB_TASK.UTC_LAST_SAVED)
UNION ALL
SELECT 
    OPB_SUBJECT.SUBJ_NAME SUBJECT_AREA, 
    OPB_TASK.TASK_NAME WORKFLOW_NAME, 
    OPB_SCHEDULER.SCHEDULER_NAME,
    OPB_SCHEDULER.START_TIME,
    OPB_SCHEDULER.END_TIME,
    OPB_SCHEDULER.IS_RUN_ON_LIMIT,
    OPB_SCHEDULER.RUN_OPTIONS,
    OPB_SCHEDULER.END_OPTIONS,
    OPB_SCHEDULER.DELTA_VALUE,
    OPB_SCHEDULER.RUN_COUNT,
    OPB_SCHEDULER.SCHEDULER_ID,
    OPB_SCHEDULER.IS_REUSABLE SCHEDULER_IS_REUSABLE,
    OPB_SCHEDULER.COMMENTS SCHEDULER_COMMENTS,
    OPB_SCHEDULER.VERSION_NUMBER SCHEDULER_VERSION_NUMBER,
    OPB_TASK.VERSION_NUMBER WORKFLOW_VERSION_NUMBER,
    OPB_TASK.TASK_ID WORKFLOW_ID, 
    OPB_TASK.SAVED_VALID WORKFLOW_IS_VALID, 
    OPB_WORKFLOW.IS_SERVICE WORKFLOW_IS_SERVICE, 
    OPB_WORKFLOW.IS_SVC_RUNNABLE WORKFLOW_IS_RUNNABLE_SERVICE, 
    OPB_TASK.LAST_SAVED WORKFLOW_LAST_SAVED, 
    OPB_TASK.COMMENTS WORKFLOW_COMMENTS,
    OPB_SUBJECT.SUBJ_ID SUBJECT_ID, 
    NULL SERVER_NAME,
    NULL SERVER_ID,
    1 WORKFLOW_IS_IMPACTED
FROM 
    OPB_TASK, OPB_SCHEDULER, OPB_WORKFLOW, OPB_SUBJECT
WHERE
    OPB_WORKFLOW.WORKFLOW_ID = OPB_TASK.TASK_ID AND
    OPB_TASK.TASK_TYPE = 71 AND
    OPB_TASK.SUBJECT_ID = OPB_SUBJECT.SUBJ_ID AND
    OPB_TASK.VERSION_NUMBER = OPB_WORKFLOW.VERSION_NUMBER AND
    OPB_TASK.IS_VISIBLE = 1 AND
    OPB_SCHEDULER.IS_VISIBLE = 1 AND
    OPB_WORKFLOW.SCHEDULER_ID = OPB_SCHEDULER.SCHEDULER_ID AND
    OPB_WORKFLOW.SERVER_ID NOT IN 
        (SELECT SERVER_ID FROM OPB_SERVER_INFO WHERE SERVER_TYPE = 41)
    AND (OPB_TASK.IS_INVALIDATED = 1
    OR EXISTS (SELECT * FROM OPB_TASK_INST I, OPB_TASK T, OPB_VALIDATE V
        WHERE OPB_TASK.TASK_ID = I.WORKFLOW_ID
        AND OPB_TASK.VERSION_NUMBER = I.VERSION_NUMBER
        AND T.TASK_ID = I.TASK_ID
        AND T.TASK_TYPE = I.TASK_TYPE
        AND T.IS_VISIBLE <> 2
        AND V.OBJECT_TYPE = T.TASK_TYPE
        AND V.OBJECT_ID = T.TASK_ID
        AND V.VERSION_NUMBER = T.VERSION_NUMBER
        AND V.INV_UTC > OPB_TASK.UTC_LAST_SAVED))
UNION ALL
SELECT 
    OPB_SUBJECT.SUBJ_NAME SUBJECT_AREA, 
    OPB_TASK.TASK_NAME WORKFLOW_NAME, 
    OPB_SCHEDULER.SCHEDULER_NAME,
    OPB_SCHEDULER.START_TIME,
    OPB_SCHEDULER.END_TIME,
    OPB_SCHEDULER.IS_RUN_ON_LIMIT,
    OPB_SCHEDULER.RUN_OPTIONS,
    OPB_SCHEDULER.END_OPTIONS,
    OPB_SCHEDULER.DELTA_VALUE,
    OPB_SCHEDULER.RUN_COUNT,
    OPB_SCHEDULER.SCHEDULER_ID,
    OPB_SCHEDULER.IS_REUSABLE SCHEDULER_IS_REUSABLE,
    OPB_SCHEDULER.COMMENTS SCHEDULER_COMMENTS,
    OPB_SCHEDULER.VERSION_NUMBER SCHEDULER_VERSION_NUMBER,
    OPB_TASK.VERSION_NUMBER WORKFLOW_VERSION_NUMBER,
    OPB_TASK.TASK_ID WORKFLOW_ID, 
    OPB_TASK.SAVED_VALID WORKFLOW_IS_VALID, 
    OPB_WORKFLOW.IS_SERVICE WORKFLOW_IS_SERVICE, 
    OPB_WORKFLOW.IS_SVC_RUNNABLE WORKFLOW_IS_RUNNABLE_SERVICE, 
    OPB_TASK.LAST_SAVED WORKFLOW_LAST_SAVED, 
    OPB_TASK.COMMENTS WORKFLOW_COMMENTS,
    OPB_SUBJECT.SUBJ_ID SUBJECT_ID, 
    NULL SERVER_NAME,
    NULL SERVER_ID,
    0 WORKFLOW_IS_IMPACTED
FROM 
    OPB_TASK, OPB_SCHEDULER, OPB_WORKFLOW, OPB_SUBJECT
WHERE
    OPB_WORKFLOW.WORKFLOW_ID = OPB_TASK.TASK_ID AND
    OPB_TASK.TASK_TYPE = 71 AND
    OPB_TASK.SUBJECT_ID = OPB_SUBJECT.SUBJ_ID AND
    OPB_TASK.VERSION_NUMBER = OPB_WORKFLOW.VERSION_NUMBER AND
    OPB_TASK.IS_VISIBLE = 1 AND
    OPB_SCHEDULER.IS_VISIBLE = 1 AND
    OPB_WORKFLOW.SCHEDULER_ID = OPB_SCHEDULER.SCHEDULER_ID AND
    OPB_WORKFLOW.SERVER_ID NOT IN 
        (SELECT SERVER_ID FROM OPB_SERVER_INFO WHERE SERVER_TYPE = 41)
    AND OPB_TASK.IS_INVALIDATED = 0
    AND NOT EXISTS (SELECT * FROM OPB_TASK_INST I, OPB_TASK T, OPB_VALIDATE V
        WHERE OPB_TASK.TASK_ID = I.WORKFLOW_ID
        AND OPB_TASK.VERSION_NUMBER = I.VERSION_NUMBER
        AND T.TASK_ID = I.TASK_ID
        AND T.TASK_TYPE = I.TASK_TYPE
        AND T.IS_VISIBLE <> 2
        AND V.OBJECT_TYPE = T.TASK_TYPE
        AND V.OBJECT_ID = T.TASK_ID
        AND V.VERSION_NUMBER = T.VERSION_NUMBER
        AND V.INV_UTC > OPB_TASK.UTC_LAST_SAVED)
UNION ALL
SELECT
    OPB_SUBJECT.SUBJ_NAME SUBJECT_AREA, 
    OPB_TASK.TASK_NAME WORKFLOW_NAME, 
    NULL SCHEDULER_NAME,
    NULL START_TIME,
    NULL END_TIME,
    NULL IS_RUN_ON_LIMIT,
    NULL RUN_OPTIONS,
    NULL END_OPTIONS,
    NULL DELTA_VALUE,
    NULL RUN_COUNT,
    NULL SCHEDULER_ID,
    NULL SCHEDULER_IS_REUSABLE,
    NULL SCHEDULER_COMMENTS,
    NULL SCHEDULER_VERSION_NUMBER,
    OPB_TASK.VERSION_NUMBER WORKFLOW_VERSION_NUMBER,
    OPB_TASK.TASK_ID WORKFLOW_ID, 
    OPB_TASK.SAVED_VALID WORKFLOW_IS_VALID, 
    OPB_WORKFLOW.IS_SERVICE WORKFLOW_IS_SERVICE, 
    OPB_WORKFLOW.IS_SVC_RUNNABLE WORKFLOW_IS_RUNNABLE_SERVICE, 
    OPB_TASK.LAST_SAVED WORKFLOW_LAST_SAVED, 
    OPB_TASK.COMMENTS WORKFLOW_COMMENTS,
    OPB_SUBJECT.SUBJ_ID SUBJECT_ID, 
    NULL SERVER_NAME,
    NULL SERVER_ID,
    1 WORKFLOW_IS_IMPACTED
FROM 
    OPB_TASK, OPB_WORKFLOW, OPB_SUBJECT
WHERE
    OPB_WORKFLOW.WORKFLOW_ID = OPB_TASK.TASK_ID AND
    OPB_TASK.TASK_TYPE = 71 AND
    OPB_TASK.SUBJECT_ID = OPB_SUBJECT.SUBJ_ID AND
    OPB_TASK.VERSION_NUMBER = OPB_WORKFLOW.VERSION_NUMBER AND
    OPB_TASK.IS_VISIBLE = 1 AND
    OPB_WORKFLOW.SCHEDULER_ID NOT IN (SELECT SCHEDULER_ID FROM OPB_SCHEDULER) AND
    OPB_WORKFLOW.SERVER_ID NOT IN 
        (SELECT SERVER_ID FROM OPB_SERVER_INFO WHERE SERVER_TYPE = 41)
    AND (OPB_TASK.IS_INVALIDATED = 1
    OR EXISTS (SELECT * FROM OPB_TASK_INST I, OPB_TASK T, OPB_VALIDATE V
        WHERE OPB_TASK.TASK_ID = I.WORKFLOW_ID
        AND OPB_TASK.VERSION_NUMBER = I.VERSION_NUMBER
        AND T.TASK_ID = I.TASK_ID
        AND T.TASK_TYPE = I.TASK_TYPE
        AND T.IS_VISIBLE <> 2
        AND V.OBJECT_TYPE = T.TASK_TYPE
        AND V.OBJECT_ID = T.TASK_ID
        AND V.VERSION_NUMBER = T.VERSION_NUMBER
        AND V.INV_UTC > OPB_TASK.UTC_LAST_SAVED))
UNION ALL
SELECT
    OPB_SUBJECT.SUBJ_NAME SUBJECT_AREA, 
    OPB_TASK.TASK_NAME WORKFLOW_NAME, 
    NULL SCHEDULER_NAME,
    NULL START_TIME,
    NULL END_TIME,
    NULL IS_RUN_ON_LIMIT,
    NULL RUN_OPTIONS,
    NULL END_OPTIONS,
    NULL DELTA_VALUE,
    NULL RUN_COUNT,
    NULL SCHEDULER_ID,
    NULL SCHEDULER_IS_REUSABLE,
    NULL SCHEDULER_COMMENTS,
    NULL SCHEDULER_VERSION_NUMBER,
    OPB_TASK.VERSION_NUMBER WORKFLOW_VERSION_NUMBER,
    OPB_TASK.TASK_ID WORKFLOW_ID, 
    OPB_TASK.SAVED_VALID WORKFLOW_IS_VALID, 
    OPB_WORKFLOW.IS_SERVICE WORKFLOW_IS_SERVICE, 
    OPB_WORKFLOW.IS_SVC_RUNNABLE WORKFLOW_IS_RUNNABLE_SERVICE, 
    OPB_TASK.LAST_SAVED WORKFLOW_LAST_SAVED, 
    OPB_TASK.COMMENTS WORKFLOW_COMMENTS,
    OPB_SUBJECT.SUBJ_ID SUBJECT_ID, 
    NULL SERVER_NAME,
    NULL SERVER_ID,
    0 WORKFLOW_IS_IMPACTED
FROM 
    OPB_TASK, OPB_WORKFLOW, OPB_SUBJECT
WHERE
    OPB_WORKFLOW.WORKFLOW_ID = OPB_TASK.TASK_ID AND
    OPB_TASK.TASK_TYPE = 71 AND
    OPB_TASK.SUBJECT_ID = OPB_SUBJECT.SUBJ_ID AND
    OPB_TASK.VERSION_NUMBER = OPB_WORKFLOW.VERSION_NUMBER AND
    OPB_TASK.IS_VISIBLE = 1 AND
    OPB_WORKFLOW.SCHEDULER_ID NOT IN (SELECT SCHEDULER_ID FROM OPB_SCHEDULER) AND
    OPB_WORKFLOW.SERVER_ID NOT IN 
        (SELECT SERVER_ID FROM OPB_SERVER_INFO WHERE SERVER_TYPE = 41)
    AND OPB_TASK.IS_INVALIDATED = 0
    AND NOT EXISTS (SELECT * FROM OPB_TASK_INST I, OPB_TASK T, OPB_VALIDATE V
        WHERE OPB_TASK.TASK_ID = I.WORKFLOW_ID
        AND OPB_TASK.VERSION_NUMBER = I.VERSION_NUMBER
        AND T.TASK_ID = I.TASK_ID
        AND T.TASK_TYPE = I.TASK_TYPE
        AND T.IS_VISIBLE <> 2
        AND V.OBJECT_TYPE = T.TASK_TYPE
        AND V.OBJECT_ID = T.TASK_ID
        AND V.VERSION_NUMBER = T.VERSION_NUMBER
        AND V.INV_UTC > OPB_TASK.UTC_LAST_SAVED) """